name: Run mabl plans on label trigger

on:
  pull_request:
    types: [labeled]

jobs:
  run-mabl-plans:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Trigger mabl plan
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          PLAN_ID: <dJNarywmfKVVwVZnx6Q6MA-p>
        run: |
          curl -X POST "https://api.mabl.com/events" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $MABL_API_KEY" \
            -d '{
                  "type": "plan",
                  "plan_id": "'"$PLAN_ID"'"
                }'
        if: ${{ github.event.label.name == 'DEPLOYMENT' }}
